### ISSUE TITLE
API Site is down

### ISSUE THREAD

**Issue by twopoint718** [MLstate/opalang#158]
The following link is broken on the main page: http://doc.opalang.org/api

**Comment by izderadicka** [comment]
Docs site is still not on -   unfortunatelly this give feeling that opa is abandoned -   that's pitty because I like  concepts of the framework.   There are some other hints which might make me cautious about using it for some project - like it does not compile under OCaml 4.02,    deb package is missing ( front page is directing me to source install),   vagrant box link is not working ...

**Comment by hbbio** [comment]
Closing, as there should be no public link anymore.
We welcome any contribution towards better documentation!
